### ISSUE TITLE
float对应支持

### ISSUE THREAD

**Issue by xiayunil** [EdgeIntelligenceChain/EdgenceChain#101]
本节点对序列化支持中，对float支持没有先天支持，导致在对float数据进行序列化的时候会产生ValueError，但是经过测试，float可以通过序列化的方式传送，需要对节点进行以下的修改
-  在utils/Utils.py中修改序列化部分，如serialize（）函数，使其支持浮点数
-  在ds/Block.py中，修改初始区块（当前初始区块时间戳为int），需要重新生成初始区块并写入为float时间戳的值，并在block定义中修改时间戳的定义为float(当前为int)
-  在EdgenceChain.py中，修改时间戳生成的定义，当前为int
目前的需求如上，如发现float错误，请加以补充

**Comment by wolfbrother** [comment]
创世区块不用变吧

**Comment by wolfbrother** [comment]
浮点数在内存中的表示，貌似有点特殊，会有一些奇葩的特性，如不能直接比较大小。
那么，那么，一个浮点数经过序列化、反序列化，会不会有精度损失，进而造成区块哈希改变而无法通过验证。这是一个问题。

可能正是这个原因，导致之前的版本里，时间戳被强制定义为int数。

**Comment by wolfbrother** [comment]
建议：时间戳产生之后，使用之前，抛掉小数点固定位数之后的小数，应该就没问题了。

比如3.141592653这个浮点数，抛掉小数点5位之后的小数，就变成了3.141590000000。
后者在反序列化、序列化过程中，应该就不会有精度损失了。

**Comment by xiayunil** [comment]
当前对float的支持主要使用保存精确的float值的方式进行,本次对float支持修改了以下位置
--
1. 修改了创世区块,将创世区块修改为生成的float值(位于ds.block中)
```python
    def genesis_block(cls):
        return cls(
            version='5465616d3a20456467656e63650a4c65616465723a20776f6c6662726f746865720a4d656d626572733a2063626f7a69'
                    '2c204c6561684c69752c207069616f6c69616e676b622c2053616c7661746f7265303632362c2053696c7669614c69313'
                    '232352c204a69617169204c69752c2078696179756e696c0a',
            prev_block_hash=None,
            merkle_hash='8cfb8d2d2ed9343461b0eefb73c775b9366a32e05e81b0e8946620e2f1935507',
            timestamp=float.fromhex('0x1.7304b0ffae89cp+30'),
            bits=Params.INITIAL_DIFFICULTY_BITS,
            nonce=19399657,
            txns=[Transaction(
                txins=[TxIn(
                    to_spend=None, unlock_sig=b'0', unlock_pk=None, sequence=0)],
                txouts=[TxOut(
                    value=5000000000, to_address='0000000000000000000000000000000000')], locktime=None)]
        )
```
2. 修改序列化以及反序列化模块,加入float支持(位于utils/Utils)
```python
elif not isinstance(o, (dict, bytes, str, int, float,type(None))):
```
3. 将目前打时间戳的函数全部修改为直接赋值,而不是强制转换为int(位于ds.block中)
