### ISSUE TITLE
接口通信数据处理出错导致余额查询失败

### ISSUE THREAD

**Issue by Dolantinlist** [EdgeIntelligenceChain/EdgenceChain#12]
client查询钱包余额，通过GetUTXOsMsg()得到的未花费交易中，所有to_address字段都为正常地址序列化后的字符串，导致地址无法比对成功，余额查询结果永远为0

**Comment by wolfbrother** [comment]
### 服务器端UTXO数据
![服务器](https://github.com/EdgeIntelligenceChain/Resources4TechDoc/blob/master/20190110-master_utxo_id.jpg)
### 客户端UTXO数据
![客户端](https://github.com/EdgeIntelligenceChain/Resources4TechDoc/blob/master/20190110-client_utxo_txid.png)

**Comment by Dolantinlist** [comment]
已修复 强制转换pubkey_to_address结果为str
https://github.com/EdgeIntelligenceChain/EdgenceChain/commit/bb0ad4acf9b20a364342092a7b23919433f4685c

**Comment by wolfbrother** [comment]
```
jin@jin-VirtualBox:~/.ssh/EdgenceChain$ python3 edgencechain.py 
[2019-01-15 11:30:48,184][edgencechain:1107] INFO generating new wallet: 'wallet.dat'
Traceback (most recent call last):
  File "edgencechain.py", line 1232, in <module>
    signing_key, verifying_key, my_address = init_wallet()
  File "edgencechain.py", line 1113, in init_wallet
    my_address = pubkey_to_address(verifying_key.to_string())
  File "edgencechain.py", line 1095, in pubkey_to_address
    return str(b58encode_check(b'\x00' + ripe), encoding='utf8')
TypeError: decoding str is not supported
```
