### ISSUE TITLE
拥有不同IP的多个节点的互联测试

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#34]

**Comment by wolfbrother** [comment]
另外查一下virtualBox里虚拟机和物理机的端口映射方式，比如最简单的，虚拟机的端口直接采用物理机的端口

**Comment by wolfbrother** [comment]
# 虚拟机的三种网络模式
  +  http://www.cnblogs.com/ggjucheng/archive/2012/08/19/2646007.html
  + 咱们用桥接模式，方便与其它虚拟机或者物理机上的节点直接联系

**Comment by SilviaLi1225** [comment]
1.	在virtualbox上新建两个虚拟机ubuntu，并配置python3.6.7环境、git、pycharm及程序所需的模块，创建本地仓库（可部署多个节点，即建立多个本地仓库）。
2.	将虚拟机的网络模式设置成桥接模式，相关内容见：https://blog.csdn.net/nsxqf/article/details/83543563，设置成功之后测试一下两台虚拟机及宿主机之间是否可以ping通，记录虚拟机的ip地址，若成功则可以进行不同ip的多节点的部署及测试。
3.	开启节点之前，修改节点的params文件夹中的Params.py文件，并且要配置一个未被占用的端口。端口的设置是在params/Params.py的PORT_CURRENT字段。 举例：将该节点的端口设置为9997： * PORT_CURRENT = int(9997)*
4.	如果该节点要与已经在运行的节点连接，则必须配置该参数，该参数位于params/Params.py的PEERS字段，节点由一个Tuple类型的(ip,port)表示其ip和port信息。可以配置多个这样的节点。 PEERS: Iterable[Tuple] = list([('127.0.0.1', 9997)])。如果想测试不同ip的节点通信，则将刚配置好的另一虚拟机的ip地址及端口写到PEERS中，如：PEERS: Iterable[Tuple] = list([(‘10.108.116.129', 9997)])
5.	初始运行的节点的block高度要最高，所以第一个启动的节点的chain.dat的文件不能删，除此之外，所有节点的wallet.dat、chain.dat及seed.node都删掉。
6.	所有节点启动后，检查每个seed.node文件中，是否有所连接节点的ip及port信息，并查看所有节点的block是否相等。
场景举例：
ubuntu1：test1及test2节点。其中两个节点配置如下：test1：初始化9997端口，连接10.108.116.129，9999端口（另一虚拟机的ip）；test2：初始化9999端口，连接localhost，9997端口.
Ubuntu2：node1节点。配置如下：node1：初始化9999端口。
首先删掉三个节点的wallet.dat及seed.node文件，删掉test1及test2的chain.dat文件，启动node1，运行一会之后，启动test1，然后启动test2。
检查三个节点的block是否相同，并检查每个节点的seed.node文件中是否含有所连接的节点的信息。
