### ISSUE TITLE
局域网端口与公网端口

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#38]
## 背景

+ 局域网内，每个主机都有一个在 *[保留IP字段](https://zh.wikipedia.org/wiki/%E4%BF%9D%E7%95%99IP%E5%9C%B0%E5%9D%80)* （如192或10开头的IP地址）
+ 一个局域网直接管辖的所有主机，可以直接通过IP进行通信。对外，这些主机共用该局域网的路由IP，只是这里的每个主机被分配了路由的不同端口，这一过程叫做*[端口映射](https://blog.csdn.net/songshiMVP1/article/details/51519767)*。可以看出，局域网内的主机不能被拥有公网IP的主机直接访问。

## 参考：
+ 一分钟实现内网穿透 https://blog.csdn.net/zhangguo5/article/details/77848658

## 问题

+ 不同局域网里的节点（以EdgenceChain的master分支的代码作为节点），如何获得对方的公网IP和端口，并建立网络连接？

**Comment by wolfbrother** [comment]
在一个虚拟机上开启两个python运行环境，然后分别用pynat请求公网IP和端口信息，竟然获得同样的返回值。
> >>> from pynat import get_ip_info
>>> get_ip_info()

**Comment by TemplarJQ** [comment]
pynat有相应内置参数。搭建公网索引服务器（ShootBack）方法测试可行，Pynat（基于STUN）存疑。

**Comment by wolfbrother** [comment]
https://github.com/EdgeIntelligenceChain/Resources4TechDoc/tree/master/20190126-local_public_net

存档，下学期继续研究这个问题。
