### ISSUE TITLE
TCP通信替换成UDP通信

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#44]
如有对状态的需求，要由请求者自己负责，对服务者透明。
``` python
    def send_to_peer(cls, data, peer)->bool:
......
            try:
                with socket.create_connection(peer(), timeout=1) as s:
                    s.sendall(cls.encode_socket_data(data))
......
```

**Comment by TemplarJQ** [comment]
# UDP通信实现
## 1.需求分析
将原本的TCP通信模式改换为UDP通信模式，且：
- 通信使用UDP方式进行；
- 分离TCPServer与UDPServer模块，使其可以在SocketServer中复用；
- 保留Message中记录发送方接收端口的属性，沿用Peer模块中peers持久化的功能；
- 检查UDP发送数据大小，有待进一步处理但不建议切片做法；
## 2.模块改动
### 2.1 通信模式图解
TCP与UDP通信方式[差别图](https://blog.csdn.net/haiersister/article/details/22167967)
### 2.2 主要改动
- EdgenceChain.py
```python
server = ThreadedUDPServer(('0.0.0.0', Params.PORT_CURRENT), UDPHandler, ···）
```
改用UDPHandler
- Utils.py
```python
@classmethod
    def send_to_peer_by_udp(cls, data, peer) -> bool:
@classmethod
    def read_udp_msg_from_socket(cls, req, gs) -> object:
```
拆解为四个类函数，并检查UDP数据块大小
- UDPServer.py
```python
    def get_request(self):
        data, client_addr = self.socket.recvfrom(self.max_packet_size)
        return (data, self.socket), client_addr
```
注意：socketserver源码中UDP模式发送方式、返回参数皆与TCP不同，已适配。
## 3.调用流程
- EdgenceChain.py启动线程-->载入UDP_handler_class
- UDP接收Param.PORT_CURRENT信息-->使用UDPserver中方法处理
- 根据peers持续通信同步
## 4.有待设计
- 解决某节点因同步区块信息过多，超出UDP发送限制，而无法连接预设节点时会单节点启动问题。
- 解决UDP发送限制问题。

**Comment by wolfbrother** [comment]
我把这个分支保护起来了，应该只有你和我可以对它修改，以防止别人误删。后边会把它合并到主分支。
