### ISSUE TITLE
localhost或者域名全部替换成IP地址

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#50]
首先判断是域名还是IP，对于域名，用socket.gethostbyname获得其IP。

下面是将域名localhost和www.baidu.com转换成IP的例子。
> In [12]: socket.gethostbyname('localhost')
Out[12]: '127.0.0.1'

> In [13]: socket.gethostbyname('www.baidu.com')
Out[13]: '111.13.100.91'

如果是网址，可以解析出域名，然后再根据上面的操作由域名获得IP。

一个解决方案是将params里面的localhost替换成127.0.0.1，不过只能在自个测试时用。不能完全避免别人也这样操作，因此需要在代码中进行检查才行。如下：
>    PEERS: Iterable[Tuple] = list([#('127.0.0.1', 2221),
>                      #('127.0.0.1', 99),
>                      ('127.0.0.1', 9999)
>                     ])

**Comment by wolfbrother** [comment]
Peer类继承了NamedTuple类，可以重写Peer的某个方法，以实现初始化时对元素进行检查吗?
如果YES，就可以把上面的解析逻辑实现在里面。

**Comment by wolfbrother** [comment]
+ 在这里解释一下你写的代码实现
+ 你的分支和其他分支的目录不一样，有可以merge的方法吗？

**Comment by wolfbrother** [comment]
做好了吗？

**Comment by xiayunil** [comment]
init_peers是初始化peer的主要函数，在init_peers插入逻辑段：
1.使用正则表达式匹配当前字段是否为ip值（使用Python的re模块）
2.对于不为ip值的，使用上面函数请求ip，并catch exception（有的字段无法解析出一个ip，如：123.aqe ）
3.成功请求ip值，按照之前代码的逻辑，将新ip append 到peers
`peers.append(Peer(str(peer[0]), int(peer[1])))`

**Comment by wolfbrother** [comment]
> init_peers是初始化peer的主要函数，在init_peers插入逻辑段：
> 1.使用正则表达式匹配当前字段是否为ip值（使用Python的re模块）
> 2.对于不为ip值的，使用上面函数请求ip，并catch exception（有的字段无法解析出一个ip，如：123.aqe ）
> 3.成功请求ip值，按照之前代码的逻辑，将新ip append 到peers
> `peers.append(Peer(str(peer[0]), int(peer[1])))`
> 
> ```python
>                     (str(peer[0]) == 'localhost' and int(peer[1]) == Params.PORT_CURRENT):
>                     pass
>                 else:
>                     #match IP address
>                     if re.match(r'(?<![\.\d])(?:25[0-5]\.|2[0-4]\d\.|[01]?\d\d?\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)(?![\.\d])',peer[0])==None:
>                         #case I,is not a IP address use DNS
>                         #replace the peer's name to the resolved name(which should be a IP addr.)
>                         #catch errors if the name is not valid
>                         try:
>                             peer[0]=socket.gethostbyname(peer[0])
>                         except Exception:
>                             logger.exception(f"[p2p] {peer[0]} can not be resolved , maybe not a valid name")
>                     else:
>                         pass
>                     #append the IP to the peers
>                     peers.append(Peer(str(peer[0]), int(peer[1])))
>             try:
>                 with open(peerfile, "wb") as f:
> ```

### 有问题，待进一步修正
#### 非IP，也非合法域名的情况 
此时，如下代码会产生异常。那么此时最终得到的peer[0]不是IP，而是一个非法的域名，而接下来仍然执行  peers.append(Peer(str(peer[0]), int(peer[1])))，而不是抛弃掉。这是不正确的。
``` python
try:
                            peer[0]=socket.gethostbyname(peer[0])
                        except Exception:
                            logger.exception(f"[p2p] {peer[0]} can not be resolved , maybe not a valid name")
```
#### 此处的更改只能检查配置文件里的域名或者IP，对于节点运行中从其它节点解析出来的peer[0]，并没有检测和修正效果。而后者，才是重点。

**Comment by wolfbrother** [comment]
把这个过程写成一个函数，放在util里面 
```python
def check_ip(ip:str)->str:
    return ip or None
```
然后各处调用它

**Comment by wolfbrother** [comment]
或者把该过程写在Peer类里面，作为Peer对象初始化时调用的方法

**Comment by xiayunil** [comment]
DNS: 主要解决名字解析（name resolve），可以使用DNS将www.baidu.com解析为111.13.100.91
python 中主要使用 socket.gethostbyname(str)对DNS进行解析
对DNS解析可能发生错误，因此要catch exception
在本项目中，p2p/peer.py中的peer对象，在其初始化时（初始化函数为init_peers）可能需要解决DNS解析任务，因此在init_peers函数中增添逻辑段
1. 由于主机默认连接127.0.0.1，对于127.0.0.1与localhost予以忽略
2. 对于非localhost的ip地址，使用正则表达式对其进行匹配，确定其是否为ip地址：
```python
re.match(r'(?<![\.\d])(?:25[0-5]\.|2[0-4]\d\.|[01]?\d\d?\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)(?![\.\d])',peer[0])==None
```
其中match为None对象，表明其非IP地址


2.1 对于非IP地址，使用 socket.gethostbyname(str)进行解析，成功解析将其添加到peers列表里面
```python
peer[0]=socket.gethostbyname(peer[0])
#append the IP to the peers
peers.append(Peer(str(peer[0]), int(peer[1])))
```
2.2 对于解析错误的IP地址，使用log记录错误信息
```python
logger.exception(f"[p2p] {peer[0]} can not be resolved , maybe not a valid name")
```
3.对于正常的IP直接添加到peers
```python
peers.append(Peer(str(peer[0]), int(peer[1])))
```

**Comment by xiayunil** [comment]
由于区块链链上节点并不可信，对于发送过来的ip地址，我们必须进行必要的验证
ip初始化由p2p/peer.py中的peer对象实现
在本项目中，p2p/peer.py中的peer对象，peer对象原本继承于type/namedTuple，不支持初始化函数，如，__new__和__init__，使用collection/namedtuple替换之前的type/namedTuple，在其初始化时（初始化函数为__new__），在__new__函数中插入DNS解析与ip：port检查代码逻辑
* DNS解析使用 socket.gethostbyname(str)
* ip：port检查使用re模块，即正则表达式
1.默认使用127.0.0.1:9999
```python
__new__(cls,ip='127.0.0.1',port=9999):
```
2.使用正则表达式对ip字段进行匹配，确定其是否为ip地址：
```python
re.match(r'(?<![\.\d])(?:25[0-5]\.|2[0-4]\d\.|[01]?\d\d?\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)(?![\.\d])',ip)==None
```
其中match为None对象，表明其非IP地址


2.1 对于非IP地址，使用 socket.gethostbyname(str)进行解析，成功解析将其添加到peers列表里面
```python
ip=socket.gethostbyname(ip)
```
2.2 对于解析错误的IP地址，使用log记录错误信息
```python
logger.exception(f"[p2p] {peer[0]} can not be resolved , maybe not a valid name")
```
3.对于解析后的ip地址，使用正则表达式验证ip与port是否正确
```python
if re.match(r'^(?<![\.\d])(?:25[0-5]\.|2[0-4]\d\.|[01]?\d\d?\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)(?![\.\d])$',ip)!=None and re.match(r'^([0-9]|[1-9]\d{1,3}|[1-5]\d{4}|6[0-4]\d{4}|65[0-4]\d{2}|655[0-2]\d|6553[0-5])$',str(port))!=None:
```
3.1 验证成功，使用super初始化peer节点
```python
return super().__new__(cls, ip, port) 
```
3.2 验证失败，使用log记录验证失败的ip地址，并返回默认地址0.0.0.0:9999
```python
#log a log if ip:port is not valid
logger.exception(f'[p2p] init peers exception：{ip}:{port} is not a valid [ip]:[port]')
#return 0.0.0.1:9999 to replace invalid ip:port, minimize loss
return super().__new__(cls,'0.0.0.0',9999)
```

**Comment by wolfbrother** [comment]
挺好。然而有一个小问题：
## 问题：
+ 异常处理里，没有返回值。那么上层函数什么也得不到。该处已经修正。

**Comment by wolfbrother** [comment]
已合并到主分支。
