### ISSUE TITLE
云上节点的部署

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#57]
在阿里云虚拟机上部署Edgence节点。
这些节点可以作为Edgence的种子节点。

**Comment by wolfbrother** [comment]
### Xmanager5

链接：https://pan.baidu.com/s/1jPPmQ3eNztAsp2LQYhSddw 
提取码：c979

**Comment by wolfbrother** [comment]
+ 打开 vim ~/.bashrc，
+ 然后再最后一行添加 export PYTHONPATH=/usr/local/python36/lib/python3.6/site-packages ， 保存
+ 执行 source ~/.bashrc

**Comment by SilviaLi1225** [comment]
# 云上节点的部署
1. 在windows上下载安装Xmanager-终端模拟管理系统来连接服务器。

   链接：https://pan.baidu.com/s/1jPPmQ3eNztAsp2LQYhSddw
提取码：c979
2. 通过快捷方式打开Xshell，点击第二行菜单栏新建会话，修改会话名称并添加主机IP地址，确定后输入需连接的服务器的账户及密码，至此连接至云服务器。

3. 下载python3.6.7源码包至home

   1. cd ..

   2. cd /home

   3. wget https://www.python.org/ftp/python36/3.6.7/Python-3.6.7.tar.xz

   4. xz -d Python-3.6.7.tar.xz

   5. tar -xf Python-3.6.7.tar

4. 安装各种依赖关系

   1. apt install libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev

   2. 如果安装时出现unable to locate package xxx,输入如下指令后再输入i的指令：
    apt-get update（更新本地软件列表）
    如果还是不行，继续输入如下指令：
    apt-get upgrade（该指令有一定风险，更新本地已安装的软件）

5. 执行配置并生成Makefile文件（构建文件）

   1. cd Python-3.6.7

   2. ./configure --prefix=/usr/local/python36 --enable-optimizations

   3. make && make install

6. 创建软链接（快捷方式）

   1. ln -s /usr/local/python36/bin/python3.6 /usr/bin/python3（如果显示已经存在python3，则使用“python3 --version”指令检查一下python3的版本是否为python3.6版本）
 
   2. ln -s /usr/local/python36/bin/pip3 /usr/bin/pip3
   
   3. ln -s /usr/local/python36/bin/2to3-3.6 /usr/bin/2to3（此步如果执行不成功貌似影响不大）

   4. “python3 --version”及“pip3 --version”检查一下是否配置成功

7. 下载安装配置git
   
   1. apt install git
   
   2. git config --global user.name xxx
   
   3. git config --global user.email xxx

   4. ssh-keygen –C “你的邮箱”，之后一直回车，同时记住生成的key保存的目录。

   5. defaults write com.apple.finder AppleShowAllFiles YES 
   
   6. 进入.ssh所在路径，cat id_rsa.pub 查看文件内容，并复制到你的github的ssh key中

8. 从github上下载代码至本地仓库
 
   1. mkdir /home/Edgence
   
   2. cd Edgence

   3. git init

   4. git remote add origin xxx

   5. git fetch origin 远程分支:本地分支

   6. git checkout 本地分支

   7. ls(可以看到该分支下的文件)

9. 运行Edgence的代码

   1. python3 main.py

   2. 如果此时报缺少ecdsa/base58的包，则输入如下指令

   3. pip3 install ecdsa/base58

   4. python3 main.py

   5. 如果此时依旧报找不到module的错，则首先使用 pip3 install ecdsa/base58的指令，检查下载的     module的位置，复制路径一直到到site-packages。
   
   6. vim ~/.bashrc

   7. 点击键盘上的insert按键，在最后一行插入 export PYTHONPATH=xxx（刚才复制的路径），然后点击键盘上的Esc按键，输入”：wq!”指令保存并退出文档编辑。
   
       一般情况下路径都为：
       export PYTHONPATH=/usr/local/python36/lib/python3.6/site-packages

   8. source ~/.bashrc 

   9. 最后执行python3 main.py
   
   10. 完成

10. 退出云服务器：logout
