### ISSUE TITLE
公网节点的双向通信

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#66]
据测试，好像有公网节点不能很好地双向通信的问题。

比如，挖到块之后，不能成功地把块发送到其它节点。比如A能给B发信息，然而B却不能给A发信息，甚至把A从其节点列表中删除。 这将阻碍节点同步。

应该不是节点的问题。

### 注：
+ xshell断开之后，开启的进程会自动断开；阿里云账户的远程连接，将网页关闭后，进程不会断。
+ 如果用xshell的话，考虑程序后台运行： https://bbs.byr.cn/#!article/Linux/157720

**Comment by wolfbrother** [comment]
文档呢？

**Comment by SilviaLi1225** [comment]
0. 手机端扫码登陆阿里云，我的工单，控制管理台选择云服务器的地点，云服务器ECS，实例，点击运程连接，输入远程连接密码：edge19

1. 如果节点在运行，使用ctrl+c停止四个节点的运行

2. 登陆xshell，连接四个云节点，分别更新四个云节点的Edgence文件下的远程master分支代码到本地分支

   1. git fetch origin master:temp
   
   2. git diff temp
   
   3. wq
   
   4. git stash
   
   5. git merge temp

   6. git branch -D temp

3.  将除上海以外的其他节点的chain.dat和mywallet.dat文件删除，并修改params文件夹中的Params文件

   - PUBLIC_IP变量赋值：该节点的公网IP
   - PORT_CURRENT设为9999（9000-11000的任意值）
   - 上海节点的PEERS中的PEERS: Iterable[Tuple]list值为空，其他节点的list中添加上海节点的IP地址及端口号

4. 重复步骤1, 登陆阿里云

5. 先运行上海节点，然后依次运行剩下的三个节点：python3 main.py

6. 关闭管理终端页面，云服务器依旧在运行
