### ISSUE TITLE
Python虚拟环境配置和安装Edgence

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#88]
目标是有类似于 https://github.com/EdgeIntelligenceChain/EdgenceHome 的Readme文件的安装配置流程，包括建立并切换到python虚拟环境、安装依赖和启动过程启动。Python配置Python3.6.7的版本。

注：目前应该是至少需要安装三个包，base58、ecdsa和bitarray。

**Comment by wolfbrother** [comment]
在readme里写详细的安装配置流程，知道建立一个单机节点。

**Comment by Dolantinlist** [comment]
https://github.com/EdgeIntelligenceChain/EdgenceChain/tree/liuying-readme
更新了readme 和requirements.txt
