### ISSUE TITLE
可执行文件编译

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#96]
将EdgenceChain编译成可执行文件，达到下载一键安装即可用的效果。不考虑参数配置，一律使用默认值。

推荐 PyInstaller工具（ https://www.pyinstaller.org/）， 已支持到Python3.7版本，支持编译成大部分Windows、Linux、Mac等系统下的可执行文件。

做两个版本的可执行文件：
+ Win 64
+ Linux 64

公网节点已经部署，作为种子节点。程序启动之后，能够通过内置的种子节点，并同步区块。

**Comment by Dolantinlist** [comment]
**### step1:python3.6.7环境安装**
	将python脚本编译为可执行文件时对当前环境有要求，在安装当前python环境时要加动态连接库(即在安装python环境时要加--enable-shared选项，否则会导致pyinstaller运行失败)。可以参考以下安装步骤。
	1）源码安装python3.6.7，源码下载地址 https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz
	2) 解压，进入源码文件夹 
		tar -xzf Python-3.6.7.tgz
		cd Python-3.6.7
	3）配置安装参数 
		./configure --enable-shared  --prefix=/usr/local/python3.6.7/
		其中 --enable-shared是必加的参数  --prefix配置的是环境安装位置 可自由修改
	4)编译安装
		make
		sudo make install
	至此，需要的python环境已安装好。
### **step2:EdgenceChain的虚拟环境建立**
	1）在EdgenceChain文件夹中建立虚拟python环境
		virtualenv --no-site-packages -p /usr/local/python3.6.7/bin/python3.6  venv
		source venv/bin/activate
	2）安装需要的依赖
		pip install -r requirements.txt 
	3) 安装pyinstaller
		pip install pyinstaller
	4) 将脚本编译为可执行文件
		pyinstaller main.py
### **step3:得到可执行文件**
	此时在我们的EdgenceChain文件夹下会新生成"build"和"dist"两个文件夹，"dist"文件夹中的"main"文件夹就是我们想要得到的结果。可进入main文件夹，运行可执行程序"main"(命令行输入./main)进行测试。
	打包后的main文件夹可进行跨平台移植。

**Comment by wolfbrother** [comment]
main是个可执行文件吗？Windows下怎么执行？Linux下怎么执行？

如果我下载到本机之后，能直接运行吗？

**Comment by Dolantinlist** [comment]
windows下打包流程：
1）配置好可运行工程的3.6.7环境，测试无误
2)  安装pyinstaller: pip install pyinstaller
3) 打包工程为一个可执行文件  pyinstaller -F main.py
在同级的dist文件夹中找到main.exe
